name: Generate Animation with 25% Probability

on:
  # Run on every push on the master branch
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate Random Number
        id: random
        run: echo "::set-output name=random::$(shuf -i 1-4 -n 1)"
        
      - name: Check Probability and Generate Animation
        if: ${{ steps.random.outputs.random == '1' }}
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Animation to the Output Branch
        if: ${{ steps.random.outputs.random == '1' }}
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
